// config.js

export const programasPredefinidos = [
  "PILA",
  "PAME",
  "PIMA",
  "UAM",
  "LLEIDA",
  "RED MARCO UNIVERSIDADES",
  "PROGRAMA DELFIN",
  "PROGRAMA DE MOVILIDAD NACIONAL E INTERNACIONAL"
];

export const carreras = [
  "ABOGADO",
  "AGROBIOTECNOLOGÍA",
  "AGRONEGOCIOS",
  "CIRUJANO DENTISTA",
  "CULTURA FISICA Y DEPORTES",
  "DESARROLLO TURISTICO SUSTENTABLE",
  "EMFERMERÍA",
  "INGENIERIA EN GEOFISICA",
  "INGENIERIA EN SISTEMAS BIOLOGICOS",
  "INGENIERIA EN TELEMATICA",
  "LETRAS HISPANICAS",
  "MEDICO CIRUJANO Y PARTERO",
  "MEDICO VETERINARIO Y ZOOTECNISTA",
  "NEGOCIOS INTERNACIONALES",
  "ENFERMERIA MODALIDAD NO ESCOLARIZADA",
  "NUTRICION",
  "PERIODISMO",
  "PSICOLOGIA",
  "SEGURIDAD LABORAL, PROTECCION CIVIL Y EMERGENCIAS",
  "TRABAJO SOCIAL"
];

export const maestria = [
    "ADMINISTRACIÓN DE NEGOCIOS",
    "CIENCIAS EN PRODUCCIÓN APÍCOLA",
    "CIENCIA DEL COMPORTAMIENTO CON ORIENTACIÓN EN ALIMENTACIÓN Y NUTRICIÓN",
    "DERECHO",
    "DESARROLLO HUMANO",
    "EDUCACIÓN E INTERCULTURALIDAD",
    "ESTUDIOS RURALES",
    "PSICOLOGÍA CON ORIENTACIÓN EN CALIDAD DE VIDA Y SALUD",
    "MAESTRÍA EN SALUD PÚBLICA",
    "TECNOLOGÍAS PARA EL APRENDIZAJE",
    "GESTIÓN PÚBLICA"
  ];

export const estancias = [
  "ESTANCIA ACADEMICA",
  "ESTANCIA DE INVESTIGACION",
  "ESTANCIA PARA PRACTICAS PROFESIONALES",
  "ESTANCIAS CORTAS (CURSO DE VERANO O INVIERNO)",
  "ESTANCIAS CORTAS PARA INVESTIGACION DE POSGRADOS"
];

export const paises = [
  "ESPAÑA",
  "ESTADOS UNIDOS",
  "CANADÁ",
  "ALEMANIA",
  "FRANCIA",
  "REINO UNIDO",
  "ITALIA",
  "BRASIL",
  "ARGENTINA",
  "CHILE",
  "COLOMBIA",
  "AUSTRALIA",
  "JAPÓN",
  "CHINA"
];

export const estadosRepublica = [
  "AGUASCALIENTES",
  "BAJA CALIFORNIA",
  "BAJA CALIFORNIA SUR",
  "CAMPECHE",
  "CHIAPAS",
  "CHIHUAHUA",
  "CIUDAD DE MÉXICO",
  "COAHUILA",
  "COLIMA",
  "DURANGO",
  "ESTADO DE MÉXICO",
  "GUANAJUATO",
  "GUERRERO",
  "HIDALGO",
  "JALISCO",
  "MICHOACÁN",
  "MORELOS",
  "NAYARIT",
  "NUEVO LEÓN",
  "OAXACA",
  "PUEBLA",
  "QUERÉTARO",
  "QUINTANA ROO",
  "SAN LUIS POTOSÍ",
  "SINALOA",
  "SONORA",
  "TABASCO",
  "TAMAULIPAS",
  "TLAXCALA",
  "VERACRUZ",
  "YUCATÁN",
  "ZACATECAS"
];

export const REGEX = {
  CODIGO: /^\d{9}$/,
  TELEFONO: /^\d{10}$/,
  NSS: /^\d{11}$/
};

export const initialFormData = {
  PROGRAMA: "",
  FOLIO: "",
  ESTADO: "ACTIVO",
  CODIGO: "",
  NOMBRE: "",
  APELLIDOS: "",
  NIVEL_ACADEMICO: "",
  CARRERA: "",
  MAESTRIA: "",
  SEMESTRE: "",
  PROMEDIO: "",
  SEXO: "",
  FECHA_NACIMIENTO: "",
  TIPO_SANGRE: "",
  NSS: "",
  TELEFONO: "",
  CORREO: "",
  CONTACTO_EMERGENCIA: "",
  NOMBRE_CONTACTO_EMERGENCIA: "",
  TIPO_MOVILIDAD: "",
  TIPO_DESTINO: "",
  INSTITUCION_DESTINO: "",
  PAIS: "",
  ESTADO_REPUBLICA: "",
  FECHA_INICIO: "",
  FECHA_FIN: "",
  OBSERVACIONES: "",
  BECADO_CUSUR: false,
  MONTO_CUSUR: "",
  DETALLES_CUSUR: "",
  BECADO_CGCI: false,
  NUMERO_BECAS_CGCI: 0,
  BECADO_PROGRAMA: false,
  MONTO_PROGRAMA: "",
  DETALLES_PROGRAMA: "",
  BECADO_EXTERNO: false,
  NUMERO_BECAS_EXTERNAS: 0,
  REVALIDACION_MATERIAS: false,
  DATOS_REVALIDACION: "",
  CERTIFICADO_CALIFICACIONES: null,
  CUENTA_CON_ALGUNA_DISCAPACIDAD: false,
  DATOS_DISCAPACIDAD: "",
  SEGURO_VIAJE: false,
  NOMBRE_ASEGURADORA: "",
  NUMERO_POLIZA: "",
  FECHA_INICIO_SEGURO: "",
  FECHA_FIN_SEGURO: "",
  CONTACTO_ASEGURADORA: "",
  OBSERVACIONES_SEGURO: "",
  EXPERIENCIA_COMPARTIDA: false,
  DETALLES_EXPERIENCIA: ""
};